02-javascript-data-types
js-tasks-ru/js-20210126_maksim15 pull request #2
Opened 2021-01-31 23:54 UTC by maximzyuzin

02-javascript-data-types/1-sort-strings - function sortStrings(arr, param),
02-javascript-data-types/2-pick - function pick(obj, fields),
02-javascript-data-types/3-omit - function omit(obj, fields)

2021-02-01 09:35 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    if (param == 'desc') {
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2021-02-01 09:36 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    for (let i = 0; i < lenArr - 1; i++) {
для сортировки массивов в JS есть встроенный метод `sort` https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/sort
пожалуйста используйте его

2021-02-01 09:38 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +        for (let i = 0; i < fields.length; i++) {
подумайте, можно ли избавиться от итерации по `fields`, возможно стоит использовать метод, который поможет проверить находится ли значение внутри массива?
Аналогичный комментарий и по решению `omit`

2021-02-01 09:38 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2021-02-01 09:53 UTC, maximzyuzin commented
> необходимо внести правки согласно комментариям

Хорошо. Принято.

2021-02-01 15:11 UTC, maximzyuzin commented on 02-javascript-data-types/1-sort-strings/index.js
> +    if (param == 'desc') {
Решение изменено на без использование метода `reverse`,

2021-02-01 15:12 UTC, maximzyuzin commented on 02-javascript-data-types/1-sort-strings/index.js
> +    for (let i = 0; i < lenArr - 1; i++) {
Решение изменено с использованием встроенного метода сортировки `sort`.

2021-02-01 17:25 UTC, maximzyuzin commented on 02-javascript-data-types/2-pick/index.js
> +        for (let i = 0; i < fields.length; i++) {
Решение изменено с использованием метода поиска в массиве `includes`.
Commit - function pick(obj, fields) - fixed

2021-02-01 17:41 UTC, maximzyuzin commented on 02-javascript-data-types/2-pick/index.js
> +        for (let i = 0; i < fields.length; i++) {
Решение задачи `omit` изменено.
Commit - function omit(obj, fields) - fixed

2021-02-01 17:48 UTC, maximzyuzin commented
Согласно комментариям все правки внесены.

2021-02-02 13:05 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +            restCompare = str1.localeCompare(str2, 'ru-en', { caseFirst: 'lower' }) * (-1);
строка 13 эквивалентна строке 15 за исключение мультипликатора (-1)
от такого дублирования кода лучше избавлятьс

2021-02-02 13:06 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    let newObj = {};
мы не переприсваиваем значение `newObj`, поэтому следует использовать `const`

2021-02-02 13:06 UTC, dosandk approved these changes
решения принимаются, посмотрите пожалуйста комментарии :mag:

2021-02-02 13:16 UTC, maximzyuzin commented on 02-javascript-data-types/1-sort-strings/index.js
> +            restCompare = str1.localeCompare(str2, 'ru-en', { caseFirst: 'lower' }) * (-1);
Нет, эти строки не эквиваленты. 
Отличие в `caseFirst` - при использовании `param = 'asc'` используется `caseFirst: 'upper'`, а при `param = 'desc'` используется `caseFirst: 'lower'`.
Как я понял условие задачи: 
_"Также функция должна учитывать регистр – строки в верхнем регистре должны идти первыми."_, то что
в не зависимости от порядка сортировки ( asc или desc), строки в  верхнем регистре должны идти первыми.
И если будет указано `caseFirst: 'upper' для `param = 'desc'`, то сроки в верхнем регистре не будут первыми.

2021-02-02 13:19 UTC, maximzyuzin commented on 02-javascript-data-types/2-pick/index.js
> +    let newObj = {};
Принято.

2021-02-04 12:13 UTC, maximzyuzin commented
На PR-те так и не запускаются авто-тесты. 
Жду когда Вы (@dosandk) смержите его вручную. Для того, чтобы открыть новый PR для задач по 3 главе задачника.

2021-02-04 14:03 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +            restCompare = str1.localeCompare(str2, 'ru-en', { caseFirst: 'lower' }) * (-1);
даже если есть зависимость на како-то параметр, данную реализацию лучше организовать через функцию:
```
const props = {
  asc: {
    direction: 1,
    options: { caseFirst: 'upper' } 
  },
  desc: {
    direction: -1,
    options: { caseFirst: 'lower' } 
  };
};
const { direction, options } = props[param];
const compare = (str1, str2, options) => {
  return str1.localeCompare(str2, 'ru-en', options);
};

return sortArr.sort((str1, str2) => {
  return direction * compare(str1, str2, options);
}
```

2021-02-04 14:03 UTC, dosandk approved these changes

2021-02-04 15:06 UTC, merged